#%% 0) Imports, configuration, and experiment constants
"""Weight-space Bayes Transport on the Greenberg et al. (2019) two-moons benchmark.

Notebook-style script: run one #%% cell at a time. There is intentionally no main().

The Bayes-Transport model no longer returns posterior particles. Instead it maps
    (input prior particle cloud, x)
onto the *weights and biases* of a small posterior-density network.

Training is simulator-supervised and likelihood-free:
    theta* ~ U([-1,1]^2)
    x ~ simulator(theta*)
    input cloud ~ one of the same three mutually-exclusive training prior sources
    density parameters = T_phi(input cloud, x)
    loss = -log q_{T_phi(input cloud,x)}(theta*)

Only T_phi is trainable. The output density network is a deterministic functional model whose
weights/biases are generated by T_phi on every inference problem.

Two output-density modes are available:
    "realnvp"          : normalized bounded-support RealNVP density (DEFAULT; true NLL)
    "unnormalized_mlp": scalar neural log-score field (experimental; no partition function)

The normalized RealNVP is initialized so that zero generated weights correspond exactly to the
Uniform([-1,1]^2) prior. This pairs naturally with the zero-initialized parameter head.
"""
from __future__ import annotations

from dataclasses import dataclass, asdict
from pathlib import Path
import csv
import json
import math
from typing import Any

import equinox as eqx
import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np
import optax

import seaborn as sns
sns.set_theme(style="whitegrid", rc={"figure.facecolor": "white", "axes.facecolor": "white"})
plt.rcParams.update({
    "mathtext.fontset": "stix",
    "font.family": "DejaVu Sans",
    "axes.titlepad": 8.0,
    "axes.labelpad": 6.0,
})

# Uncomment only when debugging numerical issues; it substantially slows JAX execution.
# jax.config.update("jax_debug_nans", True)

Array = jax.Array


@dataclass
class Config:
    # Reproducibility / outputs
    seed: int = 2028
    output_dir: str = "plots/bayes_transport_two_moons_weight_space_v4"

    # Exact two-moons benchmark
    prior_low: float = -1.0
    prior_high: float = 1.0
    radial_mean: float = 0.1
    radial_std: float = 0.01
    crescent_x_offset: float = 0.25
    observed_x1: float = 0.0
    observed_x2: float = 0.0

    # Conventional simulator-training batch: 128 independent (theta*, x) pairs.
    batch_size: int = 128

    # Input distribution encoder: preserved from the current Bayes-Transport setup.
    num_particles: int = 16 * 2
    eval_particles: int = 1024 // 2
    hidden_dim: int = 64 * 4
    heads: int = 4
    mlp_ratio: int = 4
    posterior_depth: int = 5
    posterior_conditioning: str = "cross_attention"  # {"cross_attention", "adaln"}
    max_normalized_displacement: float = 6.0  # legacy value; not used in weight-space mode
    attention_dropout_rate: float = 0.0

    # Observation encoder
    likelihood_hidden_dim: int = 64
    likelihood_heads: int = 4
    likelihood_mlp_ratio: int = 4
    likelihood_depth: int = 3
    normalize_observations: bool = True
    observation_scale: float = 1.0

    # Optimisation: preserved from the supplied/current setup.
    training_steps: int = 100_000
    learning_rate: float = 1e-5
    weight_decay: float = 1e-6
    grad_clip_norm: float = 5.0
    log_every: int = 1250

    # Generated output density. Only the Bayes-Transport hypernetwork is trainable.
    # "realnvp" is normalized and therefore uses a genuine proper logarithmic score.
    # "unnormalized_mlp" is intentionally available for experimentation/plotting, but its
    # raw -score(theta*) objective is NOT a normalized NLL and is not a proper scoring rule.
    output_density_mode: str = "realnvp"  # {"realnvp", "unnormalized_mlp"}

    # Reuse the current density-network size hyperparameters.
    posterior_density_hidden_dim: int = 64
    posterior_density_depth: int = 3

    # Kept from the current script for compatibility; not used by the two weight-space modes.
    posterior_density_components: int = 50
    posterior_density_min_scale: float = 1e-3
    posterior_density_max_abs_correlation: float = 0.95

    # Three mutually-exclusive TRAINING input-cloud sources.
    interpolation_base_cloud: str = "uniform"  # {"uniform", "gaussian"}
    prior_interpolation_probability: float = 0.25
    prior_interpolation_tau_min: float = 0.0
    prior_interpolation_tau_max: float = 2.0
    truth_anchor_probability: float = 1.0
    historical_output_prior_probability: float = 0.25
    historical_output_buffer_capacity: int = 2048

    # Exact posterior / diagnostics
    posterior_grid_size: int = 420
    exact_reference_samples: int = 10_000
    kde_grid_size: int = 220
    sliced_wasserstein_projections: int = 128

    # Figure-1-style budgets
    figure1_simulation_budgets: tuple[int, ...] = (1000, 5000, 10_000)

    # Prior-predictive plot at the very start
    prior_predictive_plot_samples: int = 30_000


CFG = Config()
OUT = Path(CFG.output_dir)
OUT.mkdir(parents=True, exist_ok=True)

if CFG.posterior_conditioning not in {"cross_attention", "adaln"}:
    raise ValueError("posterior_conditioning must be 'cross_attention' or 'adaln'.")
if CFG.hidden_dim % CFG.heads != 0:
    raise ValueError("hidden_dim must be divisible by heads.")
if CFG.likelihood_hidden_dim % CFG.likelihood_heads != 0:
    raise ValueError("likelihood_hidden_dim must be divisible by likelihood_heads.")
if CFG.interpolation_base_cloud not in {"uniform", "gaussian"}:
    raise ValueError("interpolation_base_cloud must be 'uniform' or 'gaussian'.")
if CFG.output_density_mode not in {"realnvp", "unnormalized_mlp"}:
    raise ValueError("output_density_mode must be 'realnvp' or 'unnormalized_mlp'.")
if not 0.0 <= CFG.prior_interpolation_probability <= 1.0:
    raise ValueError("prior_interpolation_probability must lie in [0,1].")
if not 0.0 <= CFG.historical_output_prior_probability <= 1.0:
    raise ValueError("historical_output_prior_probability must lie in [0,1].")
if CFG.prior_interpolation_probability + CFG.historical_output_prior_probability > 1.0 + 1e-12:
    raise ValueError(
        "prior_interpolation_probability + historical_output_prior_probability must be <= 1. "
        "The residual probability is reserved for the exact evaluation prior."
    )
if not 0.0 <= CFG.truth_anchor_probability <= 1.0:
    raise ValueError("truth_anchor_probability must lie in [0,1].")
if not 0.0 <= CFG.prior_interpolation_tau_min <= CFG.prior_interpolation_tau_max:
    raise ValueError("prior_interpolation_tau_min/max must satisfy 0 <= min <= max.")
if CFG.prior_low >= CFG.prior_high:
    raise ValueError("prior_low must be smaller than prior_high.")
if CFG.radial_std <= 0.0 or CFG.observation_scale <= 0.0:
    raise ValueError("radial_std and observation_scale must be positive.")
if CFG.posterior_density_hidden_dim < 1 or CFG.posterior_density_depth < 1:
    raise ValueError("posterior_density_hidden_dim/depth must be >= 1.")

TRAIN_EXACT_PRIOR_PROBABILITY = (
    1.0
    - CFG.prior_interpolation_probability
    - CFG.historical_output_prior_probability
)

PRIOR_CENTER = 0.5 * (CFG.prior_low + CFG.prior_high)
PRIOR_HALF_WIDTH = 0.5 * (CFG.prior_high - CFG.prior_low)
PRIOR_STD = (CFG.prior_high - CFG.prior_low) / math.sqrt(12.0)
X_OBS = np.asarray([CFG.observed_x1, CFG.observed_x2], dtype=np.float32)

plt.rcParams.update({
    "figure.facecolor": "white",
    "savefig.facecolor": "white",
    "axes.grid": True,
    "grid.alpha": 0.18,
    "axes.titlesize": 14,
    "axes.labelsize": 12,
})

print("JAX devices:", jax.devices())
print("Output directory:", OUT.resolve())
print(json.dumps(asdict(CFG), indent=2))
print(
    "Training input-cloud probabilities: "
    f"interpolate={CFG.prior_interpolation_probability:.3f}, "
    f"buffer={CFG.historical_output_prior_probability:.3f}, "
    f"exact-test-uniform={TRAIN_EXACT_PRIOR_PROBABILITY:.3f}"
)
print("Interpolation base cloud:", CFG.interpolation_base_cloud)
print("Evaluation prior: exact Uniform([-1,1]^2)")
print("Observed datum:", X_OBS)
print("Generated output density mode:", CFG.output_density_mode)
if CFG.output_density_mode == "unnormalized_mlp":
    print("WARNING: unnormalized_mlp uses a raw negative log-score, not a normalized/proper NLL.")


#%% 1) Exact two-moons simulator + FIRST plot: prior-predictive x and observed x_o

def sample_exact_prior_np(rng: np.random.Generator, n: int) -> np.ndarray:
    return rng.uniform(CFG.prior_low, CFG.prior_high, size=(int(n), 2)).astype(np.float32)


def simulate_two_moons_batch_np(rng: np.random.Generator, theta: np.ndarray) -> np.ndarray:
    theta = np.asarray(theta, dtype=np.float32)
    if theta.ndim != 2 or theta.shape[1] != 2:
        raise ValueError("theta must have shape [B,2].")

    b = theta.shape[0]
    a = rng.uniform(-0.5 * math.pi, 0.5 * math.pi, size=b).astype(np.float32)
    r = rng.normal(CFG.radial_mean, CFG.radial_std, size=b).astype(np.float32)

    p1 = r * np.cos(a) + np.float32(CFG.crescent_x_offset)
    p2 = r * np.sin(a)
    theta_sum = theta[:, 0] + theta[:, 1]
    shift1 = -np.abs(theta_sum) / np.float32(math.sqrt(2.0))
    shift2 = (-theta[:, 0] + theta[:, 1]) / np.float32(math.sqrt(2.0))
    return np.column_stack([p1 + shift1, p2 + shift2]).astype(np.float32)


def simulate_two_moons_np(rng: np.random.Generator, theta: np.ndarray) -> np.ndarray:
    return simulate_two_moons_batch_np(rng, np.asarray(theta, dtype=np.float32).reshape(1, 2))[0]


_plot_rng = np.random.default_rng(CFG.seed + 101)
_plot_theta = sample_exact_prior_np(_plot_rng, CFG.prior_predictive_plot_samples)
_plot_x = simulate_two_moons_batch_np(_plot_rng, _plot_theta)

fig, ax = plt.subplots(figsize=(7.5, 7.0))
h = ax.hist2d(_plot_x[:, 0], _plot_x[:, 1], bins=150, cmap="viridis", density=True)
ax.scatter(
    [X_OBS[0]], [X_OBS[1]], marker="*", s=260, c="white",
    edgecolors="black", linewidths=1.2, label=r"observed $x_o=(0,0)$",
)
ax.set_xlabel(r"$x_1$")
ax.set_ylabel(r"$x_2$")
ax.set_title("Two-moons prior-predictive simulator output and observed datum")
ax.set_aspect("equal", adjustable="box")
ax.legend(loc="best")
fig.colorbar(h[3], ax=ax, label="prior-predictive density")
fig.tight_layout()
fig.savefig(OUT / "00_observed_x_prior_predictive.png", dpi=180, bbox_inches="tight")
plt.show()


#%% 2) Training-only input-cloud mixture and historical posterior-cloud buffer

def sample_interpolation_base_cloud_np(
    rng: np.random.Generator,
    n: int,
    cfg: Config = CFG,
) -> np.ndarray:
    if cfg.interpolation_base_cloud == "uniform":
        return sample_exact_prior_np(rng, n)
    return rng.normal(loc=PRIOR_CENTER, scale=PRIOR_STD, size=(int(n), 2)).astype(np.float32)


def sample_interpolated_training_prior_np(
    rng: np.random.Generator,
    theta_target: np.ndarray,
    cfg: Config = CFG,
) -> tuple[np.ndarray, float]:
    z = sample_interpolation_base_cloud_np(rng, cfg.num_particles, cfg)
    if rng.random() < cfg.truth_anchor_probability:
        anchor = np.asarray(theta_target, dtype=np.float32).reshape(2)
    else:
        anchor = sample_exact_prior_np(rng, 1)[0]
    tau = float(rng.uniform(cfg.prior_interpolation_tau_min, cfg.prior_interpolation_tau_max))
    cloud = (1.0 - tau) * z + tau * anchor[None, :]
    return cloud.astype(np.float32), tau


class HistoricalPosteriorBuffer:
    """Stores an observation x and a detached cloud sampled from the previously generated density."""

    def __init__(self, capacity: int, num_particles: int):
        self.capacity = int(capacity)
        self.num_particles = int(num_particles)
        self.x = np.empty((self.capacity, 2), dtype=np.float32)
        self.clouds = np.empty((self.capacity, self.num_particles, 2), dtype=np.float32)
        self.size = 0
        self.next_index = 0

    def __len__(self) -> int:
        return int(self.size)

    @property
    def active_x(self) -> np.ndarray:
        return self.x[: self.size]

    @property
    def active_clouds(self) -> np.ndarray:
        return self.clouds[: self.size]

    def add_batch(self, x: np.ndarray, clouds: np.ndarray) -> None:
        x = np.asarray(x, dtype=np.float32)
        clouds = np.asarray(clouds, dtype=np.float32)
        if clouds.shape != (len(x), self.num_particles, 2):
            raise ValueError(
                f"clouds must have shape {(len(x), self.num_particles, 2)}, got {clouds.shape}."
            )
        for xi, cloud in zip(x, clouds):
            self.x[self.next_index] = xi
            self.clouds[self.next_index] = cloud
            self.next_index = (self.next_index + 1) % self.capacity
            self.size = min(self.size + 1, self.capacity)

    def nearest_batch(self, x_query: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        if self.size == 0:
            raise ValueError("HistoricalPosteriorBuffer is empty.")
        x_query = np.asarray(x_query, dtype=np.float32).reshape(-1, 2)
        delta = (x_query[:, None, :] - self.active_x[None, :, :]) / float(CFG.observation_scale)
        d2 = np.sum(delta**2, axis=-1)
        ids = np.argmin(d2, axis=1)
        distances = np.sqrt(d2[np.arange(len(x_query)), ids])
        return self.active_clouds[ids].copy(), distances.astype(np.float32)


def make_training_prior_batch_np(
    rng: np.random.Generator,
    mode_rng: np.random.Generator,
    theta_target: np.ndarray,
    x_batch: np.ndarray,
    replay_buffer: HistoricalPosteriorBuffer,
    cfg: Config = CFG,
) -> tuple[np.ndarray, dict[str, np.ndarray]]:
    """Choose exactly one input-cloud source independently for each training inference problem."""
    theta_target = np.asarray(theta_target, dtype=np.float32)
    x_batch = np.asarray(x_batch, dtype=np.float32)
    b = theta_target.shape[0]

    prior = np.empty((b, cfg.num_particles, 2), dtype=np.float32)
    u = mode_rng.random(b)
    p_interp = cfg.prior_interpolation_probability
    p_buffer = cfg.historical_output_prior_probability

    interp_mask = u < p_interp
    requested_buffer_mask = (u >= p_interp) & (u < p_interp + p_buffer)
    buffer_mask = requested_buffer_mask & (len(replay_buffer) > 0)
    exact_mask = ~(interp_mask | buffer_mask)

    tau = np.zeros(b, dtype=np.float32)
    replay_distance = np.full(b, np.nan, dtype=np.float32)

    for i in np.flatnonzero(interp_mask):
        prior[i], tau[i] = sample_interpolated_training_prior_np(rng, theta_target[i], cfg)

    buffer_ids = np.flatnonzero(buffer_mask)
    if len(buffer_ids):
        clouds, dist = replay_buffer.nearest_batch(x_batch[buffer_ids])
        prior[buffer_ids] = clouds
        replay_distance[buffer_ids] = dist

    exact_ids = np.flatnonzero(exact_mask)
    if len(exact_ids):
        prior[exact_ids] = sample_exact_prior_np(
            rng, len(exact_ids) * cfg.num_particles
        ).reshape(len(exact_ids), cfg.num_particles, 2)

    return prior, {
        "interpolation_used": interp_mask.astype(np.float32),
        "buffer_used": buffer_mask.astype(np.float32),
        "exact_prior_used": exact_mask.astype(np.float32),
        "interpolation_tau": tau,
        "replay_distance": replay_distance,
    }


#%% 3) JAX + Equinox weight-space Bayes Transport

def _linear_tokens(layer: eqx.nn.Linear, x: Array) -> Array:
    return jax.vmap(layer)(x)


def _layernorm_tokens(layer: eqx.nn.LayerNorm, x: Array) -> Array:
    return jax.vmap(layer)(x)


def _modulate(x: Array, shift: Array, scale: Array) -> Array:
    return x * (1.0 + scale[None, :]) + shift[None, :]


class ObservationBlock(eqx.Module):
    norm1: eqx.nn.LayerNorm
    norm2: eqx.nn.LayerNorm
    attention: eqx.nn.MultiheadAttention
    ff_in: eqx.nn.Linear
    ff_out: eqx.nn.Linear

    def __init__(self, dim: int, heads: int, mlp_dim: int, dropout_p: float, *, key: Array):
        k_attn, k_ff1, k_ff2 = jax.random.split(key, 3)
        self.norm1 = eqx.nn.LayerNorm(dim)
        self.norm2 = eqx.nn.LayerNorm(dim)
        self.attention = eqx.nn.MultiheadAttention(
            num_heads=heads, query_size=dim, key_size=dim, value_size=dim,
            output_size=dim, dropout_p=dropout_p, key=k_attn,
        )
        self.ff_in = eqx.nn.Linear(dim, mlp_dim, key=k_ff1)
        self.ff_out = eqx.nn.Linear(mlp_dim, dim, key=k_ff2)

    def __call__(self, tokens: Array, *, key: Array | None = None, inference: bool = False) -> Array:
        h = _layernorm_tokens(self.norm1, tokens)
        tokens = tokens + self.attention(h, h, h, key=key, inference=inference)
        h = _layernorm_tokens(self.norm2, tokens)
        h = jax.nn.gelu(_linear_tokens(self.ff_in, h))
        return tokens + _linear_tokens(self.ff_out, h)


class TwoMoonsObservationEmbedder(eqx.Module):
    input_projection: eqx.nn.Linear
    blocks: tuple[ObservationBlock, ...]
    final_norm: eqx.nn.LayerNorm
    normalize: bool = eqx.field(static=True)
    scale: float = eqx.field(static=True)

    def __init__(self, cfg: Config, *, key: Array):
        keys = jax.random.split(key, cfg.likelihood_depth + 1)
        self.input_projection = eqx.nn.Linear(3, cfg.likelihood_hidden_dim, key=keys[0])
        self.blocks = tuple(
            ObservationBlock(
                cfg.likelihood_hidden_dim,
                cfg.likelihood_heads,
                cfg.likelihood_mlp_ratio * cfg.likelihood_hidden_dim,
                cfg.attention_dropout_rate,
                key=keys[i + 1],
            )
            for i in range(cfg.likelihood_depth)
        )
        self.final_norm = eqx.nn.LayerNorm(cfg.likelihood_hidden_dim)
        self.normalize = bool(cfg.normalize_observations)
        self.scale = float(cfg.observation_scale)

    def __call__(self, x: Array, *, key: Array | None = None, inference: bool = False) -> Array:
        x = jnp.reshape(x, (2,))
        if self.normalize:
            x = x / self.scale
        coord_id = jnp.eye(2, dtype=x.dtype)
        token_features = jnp.concatenate([x[:, None], coord_id], axis=-1)
        tokens = _linear_tokens(self.input_projection, token_features)
        block_keys = None if key is None else jax.random.split(key, len(self.blocks))
        for i, block in enumerate(self.blocks):
            tokens = block(
                tokens,
                key=None if block_keys is None else block_keys[i],
                inference=inference,
            )
        return _layernorm_tokens(self.final_norm, tokens)


class AdaLNParticleBlock(eqx.Module):
    norm_attn: eqx.nn.LayerNorm
    norm_ff: eqx.nn.LayerNorm
    attention: eqx.nn.MultiheadAttention
    ff_in: eqx.nn.Linear
    ff_out: eqx.nn.Linear
    modulation: eqx.nn.Linear

    def __init__(
        self, hidden: int, conditioning_dim: int, heads: int,
        mlp_dim: int, dropout_p: float, *, key: Array,
    ):
        k_attn, k_ff1, k_ff2, k_mod = jax.random.split(key, 4)
        self.norm_attn = eqx.nn.LayerNorm(hidden)
        self.norm_ff = eqx.nn.LayerNorm(hidden)
        self.attention = eqx.nn.MultiheadAttention(
            num_heads=heads, query_size=hidden, key_size=hidden, value_size=hidden,
            output_size=hidden, dropout_p=dropout_p, key=k_attn,
        )
        self.ff_in = eqx.nn.Linear(hidden, mlp_dim, key=k_ff1)
        self.ff_out = eqx.nn.Linear(mlp_dim, hidden, key=k_ff2)
        modulation = eqx.nn.Linear(conditioning_dim, 6 * hidden, key=k_mod)
        modulation = eqx.tree_at(lambda l: l.weight, modulation, jnp.zeros_like(modulation.weight))
        modulation = eqx.tree_at(lambda l: l.bias, modulation, jnp.zeros_like(modulation.bias))
        self.modulation = modulation

    def __call__(
        self, particles: Array, conditioning: Array, *,
        key: Array | None = None, inference: bool = False,
    ) -> Array:
        shift_a, scale_a, gate_a, shift_f, scale_f, gate_f = jnp.split(
            self.modulation(jax.nn.silu(conditioning)), 6, axis=-1
        )
        h = _modulate(_layernorm_tokens(self.norm_attn, particles), shift_a, scale_a)
        particles = particles + gate_a[None, :] * self.attention(
            h, h, h, key=key, inference=inference
        )
        h = _modulate(_layernorm_tokens(self.norm_ff, particles), shift_f, scale_f)
        h = jax.nn.gelu(_linear_tokens(self.ff_in, h))
        return particles + gate_f[None, :] * _linear_tokens(self.ff_out, h)


class CrossAttentionParticleBlock(eqx.Module):
    norm_self: eqx.nn.LayerNorm
    norm_cross: eqx.nn.LayerNorm
    memory_norm: eqx.nn.LayerNorm
    norm_ff: eqx.nn.LayerNorm
    self_attention: eqx.nn.MultiheadAttention
    cross_attention: eqx.nn.MultiheadAttention
    ff_in: eqx.nn.Linear
    ff_out: eqx.nn.Linear

    def __init__(
        self, hidden: int, memory_dim: int, heads: int,
        mlp_dim: int, dropout_p: float, *, key: Array,
    ):
        k_self, k_cross, k_ff1, k_ff2 = jax.random.split(key, 4)
        self.norm_self = eqx.nn.LayerNorm(hidden)
        self.norm_cross = eqx.nn.LayerNorm(hidden)
        self.memory_norm = eqx.nn.LayerNorm(memory_dim)
        self.norm_ff = eqx.nn.LayerNorm(hidden)
        self.self_attention = eqx.nn.MultiheadAttention(
            num_heads=heads, query_size=hidden, key_size=hidden, value_size=hidden,
            output_size=hidden, dropout_p=dropout_p, key=k_self,
        )
        self.cross_attention = eqx.nn.MultiheadAttention(
            num_heads=heads, query_size=hidden, key_size=memory_dim, value_size=memory_dim,
            output_size=hidden, dropout_p=dropout_p, key=k_cross,
        )
        self.ff_in = eqx.nn.Linear(hidden, mlp_dim, key=k_ff1)
        self.ff_out = eqx.nn.Linear(mlp_dim, hidden, key=k_ff2)

    def __call__(
        self, particles: Array, observation_memory: Array, *,
        key: Array | None = None, inference: bool = False,
    ) -> Array:
        if key is None:
            self_key = cross_key = None
        else:
            self_key, cross_key = jax.random.split(key)
        h = _layernorm_tokens(self.norm_self, particles)
        particles = particles + self.self_attention(h, h, h, key=self_key, inference=inference)
        q = _layernorm_tokens(self.norm_cross, particles)
        memory = _layernorm_tokens(self.memory_norm, observation_memory)
        particles = particles + self.cross_attention(
            q, memory, memory, key=cross_key, inference=inference
        )
        h = _layernorm_tokens(self.norm_ff, particles)
        h = jax.nn.gelu(_linear_tokens(self.ff_in, h))
        return particles + _linear_tokens(self.ff_out, h)


# Generated density parameter counts ---------------------------------------------------------------

def generated_mlp_parameter_count(in_dim: int, hidden: int, depth: int, out_dim: int) -> int:
    total = 0
    d = int(in_dim)
    for _ in range(int(depth)):
        total += int(hidden) * d + int(hidden)
        d = int(hidden)
    total += int(out_dim) * d + int(out_dim)
    return int(total)


REALNVP_COUPLINGS = max(2, 2 * int(CFG.posterior_density_depth))
REALNVP_COUPLING_PARAMETER_COUNT = generated_mlp_parameter_count(
    1, CFG.posterior_density_hidden_dim, CFG.posterior_density_depth, 2
)
REALNVP_PARAMETER_COUNT = REALNVP_COUPLINGS * REALNVP_COUPLING_PARAMETER_COUNT
UNNORMALIZED_PARAMETER_COUNT = generated_mlp_parameter_count(
    2, CFG.posterior_density_hidden_dim, CFG.posterior_density_depth, 1
)
DENSITY_PARAMETER_COUNT = (
    REALNVP_PARAMETER_COUNT
    if CFG.output_density_mode == "realnvp"
    else UNNORMALIZED_PARAMETER_COUNT
)


class WeightSpaceBayesTransport(eqx.Module):
    """Particle-cloud Transformer -> sequence of generated density parameters [P,1].

    The input is a sequence of M particles in R^2. The particle Transformer processes this
    distribution while conditioning on x. The resulting particle sequence is pooled into one cloud
    representation, then a single hypernetwork head emits all P scalar weights/biases of the output
    density. Reshaping to [P,1] makes the output explicitly a scalar parameter sequence.
    """

    observation_embedder: TwoMoonsObservationEmbedder
    particle_in: eqx.nn.Linear
    blocks: tuple[Any, ...]
    final_norm: eqx.nn.LayerNorm
    parameter_head: eqx.nn.Linear

    conditioning_type: str = eqx.field(static=True)
    prior_center: float = eqx.field(static=True)
    prior_std: float = eqx.field(static=True)
    n_density_parameters: int = eqx.field(static=True)

    def __init__(self, cfg: Config, *, key: Array):
        keys = jax.random.split(key, cfg.posterior_depth + 4)
        self.observation_embedder = TwoMoonsObservationEmbedder(cfg, key=keys[0])
        self.particle_in = eqx.nn.Linear(2, cfg.hidden_dim, key=keys[1])
        block_cls = AdaLNParticleBlock if cfg.posterior_conditioning == "adaln" else CrossAttentionParticleBlock
        self.blocks = tuple(
            block_cls(
                cfg.hidden_dim,
                cfg.likelihood_hidden_dim,
                cfg.heads,
                cfg.mlp_ratio * cfg.hidden_dim,
                cfg.attention_dropout_rate,
                key=keys[2 + i],
            )
            for i in range(cfg.posterior_depth)
        )
        self.final_norm = eqx.nn.LayerNorm(cfg.hidden_dim)

        # All generated density weights/biases are emitted at once. Zero initialization is deliberate:
        # in realnvp mode, all-zero generated coupling networks give the exact Uniform([-1,1]^2) prior.
        head = eqx.nn.Linear(cfg.hidden_dim, DENSITY_PARAMETER_COUNT, key=keys[-1])
        head = eqx.tree_at(lambda l: l.weight, head, jnp.zeros_like(head.weight))
        head = eqx.tree_at(lambda l: l.bias, head, jnp.zeros_like(head.bias))
        self.parameter_head = head

        self.conditioning_type = str(cfg.posterior_conditioning)
        self.prior_center = float(PRIOR_CENTER)
        self.prior_std = float(PRIOR_STD)
        self.n_density_parameters = int(DENSITY_PARAMETER_COUNT)

    def _standardize(self, theta: Array) -> Array:
        return (theta - self.prior_center) / self.prior_std

    def __call__(
        self,
        prior_theta: Array,
        x: Array,
        *,
        key: Array | None = None,
        inference: bool = False,
    ) -> Array:
        if key is None:
            obs_key = None
            transport_key = None
        else:
            obs_key, transport_key = jax.random.split(key)

        memory = self.observation_embedder(x, key=obs_key, inference=inference)
        particles = _linear_tokens(self.particle_in, self._standardize(prior_theta))
        block_keys = None if transport_key is None else jax.random.split(transport_key, len(self.blocks))

        if self.conditioning_type == "adaln":
            conditioning = jnp.mean(memory, axis=0)
            for i, block in enumerate(self.blocks):
                particles = block(
                    particles,
                    conditioning,
                    key=None if block_keys is None else block_keys[i],
                    inference=inference,
                )
        else:
            for i, block in enumerate(self.blocks):
                particles = block(
                    particles,
                    memory,
                    key=None if block_keys is None else block_keys[i],
                    inference=inference,
                )

        particles = _layernorm_tokens(self.final_norm, particles)
        cloud_state = jnp.mean(particles, axis=0)
        flat_parameters = self.parameter_head(cloud_state)
        return flat_parameters[:, None]  # [number_of_weights_and_biases, 1]


print("Generated density parameter count:", DENSITY_PARAMETER_COUNT)
if CFG.output_density_mode == "realnvp":
    print(
        f"RealNVP: {REALNVP_COUPLINGS} coupling MLPs; "
        f"{REALNVP_COUPLING_PARAMETER_COUNT} generated scalars per coupling."
    )
else:
    print("Unnormalized scalar MLP generated parameter count:", UNNORMALIZED_PARAMETER_COUNT)


#%% 4) Reconstituted density functional + NLL objective + single optimiser

def _generated_mlp_apply(
    flat: Array,
    value: Array,
    *,
    in_dim: int,
    hidden_dim: int,
    depth: int,
    out_dim: int,
) -> Array:
    """Apply an MLP whose complete weights/biases are stored in one flat vector."""
    h = jnp.reshape(value, (int(in_dim),))
    offset = 0
    d = int(in_dim)

    for _ in range(int(depth)):
        n_w = int(hidden_dim) * d
        w = flat[offset:offset + n_w].reshape((int(hidden_dim), d))
        offset += n_w
        b = flat[offset:offset + int(hidden_dim)]
        offset += int(hidden_dim)
        h = jax.nn.gelu(w @ h + b)
        d = int(hidden_dim)

    n_w = int(out_dim) * d
    w = flat[offset:offset + n_w].reshape((int(out_dim), d))
    offset += n_w
    b = flat[offset:offset + int(out_dim)]
    return w @ h + b


def _realnvp_coupling(flat_parameters: Array, layer_index: int, conditioner: Array) -> tuple[Array, Array]:
    start = int(layer_index) * REALNVP_COUPLING_PARAMETER_COUNT
    stop = start + REALNVP_COUPLING_PARAMETER_COUNT
    raw_shift, raw_log_scale = _generated_mlp_apply(
        flat_parameters[start:stop],
        jnp.reshape(conditioner, (1,)),
        in_dim=1,
        hidden_dim=CFG.posterior_density_hidden_dim,
        depth=CFG.posterior_density_depth,
        out_dim=2,
    )
    # Fixed numerical safeguard inherited from the previous RealNVP version.
    log_scale = 2.0 * jnp.tanh(raw_log_scale)
    return raw_shift, log_scale


def _log_cosh(x: Array) -> Array:
    a = jnp.abs(x)
    return a + jax.nn.softplus(-2.0 * a) - math.log(2.0)


def generated_realnvp_log_prob(flat_parameters: Array, theta: Array) -> Array:
    """Normalized log density on the exact prior support [-1,1]^2.

    The outer tanh map gives compact support. The base density is chosen as
        f(z)=0.5*sech(z)^2
    independently in each coordinate. Therefore when every generated coupling weight is zero,
    tanh(z) is exactly Uniform(-1,1), so the whole initial output density is exactly the paper prior.
    """
    theta = jnp.asarray(theta)

    def one_log_prob(th: Array) -> Array:
        u = (jnp.reshape(th, (2,)) - PRIOR_CENTER) / PRIOR_HALF_WIDTH
        inside = jnp.all(jnp.abs(u) < 1.0)
        safe_u = jnp.clip(u, -1.0 + 1e-6, 1.0 - 1e-6)
        y = jnp.arctanh(safe_u)

        # theta -> y Jacobian from theta = center + half_width*tanh(y)
        log_abs_det_inverse = jnp.sum(
            -math.log(PRIOR_HALF_WIDTH) - jnp.log1p(-safe_u**2)
        )

        # Invert generated affine couplings y -> z.
        for layer_index in range(REALNVP_COUPLINGS - 1, -1, -1):
            transformed = layer_index % 2
            conditioner_idx = 1 - transformed
            shift, log_scale = _realnvp_coupling(
                flat_parameters, layer_index, y[conditioner_idx]
            )
            y = y.at[transformed].set((y[transformed] - shift) * jnp.exp(-log_scale))
            log_abs_det_inverse = log_abs_det_inverse - log_scale

        # Base f(z)=0.5 sech(z)^2 independently in each dimension.
        base_log_prob = jnp.sum(-math.log(2.0) - 2.0 * _log_cosh(y))
        value = base_log_prob + log_abs_det_inverse
        return jnp.where(inside, value, -jnp.inf)

    flat_theta = theta.reshape((-1, 2))
    values = jax.vmap(one_log_prob)(flat_theta)
    return values.reshape(theta.shape[:-1])


def generated_realnvp_sample(flat_parameters: Array, key: Array, n: int) -> Array:
    """Exact samples from the generated bounded-support RealNVP density."""
    # If U~Uniform(-1,1), atanh(U) has density 0.5 sech(z)^2: our chosen base.
    u0 = jax.random.uniform(key, (int(n), 2), minval=-1.0 + 1e-6, maxval=1.0 - 1e-6)
    z = jnp.arctanh(u0)

    def forward_one(z0: Array) -> Array:
        y = z0
        for layer_index in range(REALNVP_COUPLINGS):
            transformed = layer_index % 2
            conditioner_idx = 1 - transformed
            shift, log_scale = _realnvp_coupling(
                flat_parameters, layer_index, y[conditioner_idx]
            )
            y = y.at[transformed].set(y[transformed] * jnp.exp(log_scale) + shift)
        return PRIOR_CENTER + PRIOR_HALF_WIDTH * jnp.tanh(y)

    return jax.vmap(forward_one)(z)


def generated_unnormalized_log_score(flat_parameters: Array, theta: Array) -> Array:
    """Unnormalized neural log-score s_w(theta). There is deliberately no partition function."""
    theta = jnp.asarray(theta)

    def one_score(th: Array) -> Array:
        standardized = (jnp.reshape(th, (2,)) - PRIOR_CENTER) / PRIOR_STD
        return _generated_mlp_apply(
            flat_parameters,
            standardized,
            in_dim=2,
            hidden_dim=CFG.posterior_density_hidden_dim,
            depth=CFG.posterior_density_depth,
            out_dim=1,
        )[0]

    flat_theta = theta.reshape((-1, 2))
    values = jax.vmap(one_score)(flat_theta)
    return values.reshape(theta.shape[:-1])


def generated_density_log_value(flat_parameters: Array, theta: Array) -> Array:
    if CFG.output_density_mode == "realnvp":
        return generated_realnvp_log_prob(flat_parameters, theta)
    return generated_unnormalized_log_score(flat_parameters, theta)


def weight_space_objective(
    model: WeightSpaceBayesTransport,
    prior_theta: Array,
    x_batch: Array,
    target_theta: Array,
    dropout_key: Array,
):
    """One loss only: target NLL for normalized mode, or raw negative score for unnormalized mode."""
    row_keys = jax.random.split(dropout_key, prior_theta.shape[0])
    parameter_sequence = jax.vmap(
        lambda p, x, k: model(p, x, key=k, inference=False)
    )(prior_theta, x_batch, row_keys)  # [B,P,1]
    flat_parameters = parameter_sequence[..., 0]

    target_log_value = jax.vmap(generated_density_log_value)(flat_parameters, target_theta)
    loss = -jnp.mean(target_log_value)

    rms_parameters = jnp.sqrt(jnp.mean(flat_parameters**2) + 1e-12)
    max_abs_parameters = jnp.max(jnp.abs(flat_parameters))
    metrics = {
        "loss": loss,
        "target_nll": loss,
        "mean_target_log_value": jnp.mean(target_log_value),
        "target_log_value_std": jnp.std(target_log_value),
        "generated_parameter_rms": rms_parameters,
        "generated_parameter_max_abs": max_abs_parameters,
    }
    return loss, (metrics, parameter_sequence)


_loss_and_grad = eqx.filter_value_and_grad(weight_space_objective, has_aux=True)


def make_train_step(optimizer: optax.GradientTransformation):
    @eqx.filter_jit
    def step(model, opt_state, prior_theta, x_batch, target_theta, dropout_key):
        (loss, (metrics, parameter_sequence)), grads = _loss_and_grad(
            model, prior_theta, x_batch, target_theta, dropout_key
        )
        params = eqx.filter(model, eqx.is_array)
        updates, opt_state = optimizer.update(grads, opt_state, params)
        model = eqx.apply_updates(model, updates)
        grad_norm = optax.global_norm(eqx.filter(grads, eqx.is_array))
        return model, opt_state, loss, metrics, parameter_sequence, grad_norm
    return step


def _sample_replay_cloud_one(flat_parameters: Array, key: Array) -> Array:
    if CFG.output_density_mode == "realnvp":
        return generated_realnvp_sample(flat_parameters, key, CFG.num_particles)

    # The unnormalized mode has no exact sampler. For replay ONLY, use importance-resampling from
    # a fixed-size Uniform([-1,1]^2) candidate pool. This does not enter the training loss.
    key_candidates, key_indices = jax.random.split(key)
    candidate_count = max(128, 4 * CFG.num_particles)
    candidates = jax.random.uniform(
        key_candidates,
        (candidate_count, 2),
        minval=CFG.prior_low,
        maxval=CFG.prior_high,
    )
    scores = generated_unnormalized_log_score(flat_parameters, candidates)
    ids = jax.random.categorical(key_indices, scores, shape=(CFG.num_particles,))
    return candidates[ids]


@jax.jit
def sample_replay_cloud_batch(flat_parameters: Array, key: Array) -> Array:
    keys = jax.random.split(key, flat_parameters.shape[0])
    return jax.vmap(_sample_replay_cloud_one)(flat_parameters, keys)


model = WeightSpaceBayesTransport(CFG, key=jax.random.key(CFG.seed))
optimizer = optax.chain(
    optax.clip_by_global_norm(CFG.grad_clip_norm),
    optax.adamw(CFG.learning_rate, weight_decay=CFG.weight_decay),
)
opt_state = optimizer.init(eqx.filter(model, eqx.is_array))
train_step = make_train_step(optimizer)

print("Weight-space Bayes Transport initialized.")
print("Conditioning:", CFG.posterior_conditioning)
print("Training batch size:", CFG.batch_size)
print("Input particles per inference problem:", CFG.num_particles)
print("Output parameter sequence shape per problem:", (DENSITY_PARAMETER_COUNT, 1))
print("Only trainable object: WeightSpaceBayesTransport")


#%% 5) Exact posterior + direct density evaluation + plotting/metrics utilities

def normal_pdf_sd_np(x: np.ndarray, mean: float, std: float) -> np.ndarray:
    z = (np.asarray(x, dtype=np.float64) - float(mean)) / float(std)
    return np.exp(-0.5 * z**2) / (float(std) * math.sqrt(2.0 * math.pi))


def crescent_p_density_np(p: np.ndarray, cfg: Config = CFG) -> np.ndarray:
    p = np.asarray(p, dtype=np.float64)
    u = p[..., 0] - float(cfg.crescent_x_offset)
    v = p[..., 1]
    rho = np.sqrt(u**2 + v**2)
    rho_safe = np.maximum(rho, 1e-12)
    signed_r = np.where(u >= 0.0, rho, -rho)
    density = normal_pdf_sd_np(signed_r, cfg.radial_mean, cfg.radial_std) / (math.pi * rho_safe)
    return np.where(rho > 1e-12, density, 0.0)


def two_moons_likelihood_density_np(x: np.ndarray, theta: np.ndarray, cfg: Config = CFG) -> np.ndarray:
    x = np.asarray(x, dtype=np.float64).reshape(2)
    theta = np.asarray(theta, dtype=np.float64)
    theta_sum = theta[..., 0] + theta[..., 1]
    shift1 = -np.abs(theta_sum) / math.sqrt(2.0)
    shift2 = (-theta[..., 0] + theta[..., 1]) / math.sqrt(2.0)
    p_required = np.stack([x[0] - shift1, x[1] - shift2], axis=-1)
    return crescent_p_density_np(p_required, cfg)


def exact_posterior_grid(x: np.ndarray = X_OBS, cfg: Config = CFG):
    t1 = np.linspace(cfg.prior_low, cfg.prior_high, cfg.posterior_grid_size, dtype=np.float64)
    t2 = np.linspace(cfg.prior_low, cfg.prior_high, cfg.posterior_grid_size, dtype=np.float64)
    g1, g2 = np.meshgrid(t1, t2, indexing="xy")
    theta = np.stack([g1, g2], axis=-1)
    density = two_moons_likelihood_density_np(x, theta, cfg)
    d1, d2 = t1[1] - t1[0], t2[1] - t2[0]
    z = np.sum(density) * d1 * d2
    if not np.isfinite(z) or z <= 0.0:
        raise FloatingPointError("Ground-truth posterior grid failed to normalize.")
    return t1, t2, density / z


def sample_from_grid_posterior(
    rng: np.random.Generator,
    theta1: np.ndarray,
    theta2: np.ndarray,
    density: np.ndarray,
    n: int,
) -> np.ndarray:
    p = np.asarray(density, dtype=np.float64).reshape(-1)
    p /= p.sum()
    ids = rng.choice(len(p), size=int(n), replace=True, p=p)
    i2, i1 = np.unravel_index(ids, density.shape)
    samples = np.column_stack([theta1[i1], theta2[i2]]).astype(np.float64)
    d1, d2 = theta1[1] - theta1[0], theta2[1] - theta2[0]
    samples[:, 0] += rng.uniform(-0.5 * d1, 0.5 * d1, size=len(samples))
    samples[:, 1] += rng.uniform(-0.5 * d2, 0.5 * d2, size=len(samples))
    return samples.astype(np.float32)


def credible_density_levels(density: np.ndarray, masses=(0.50, 0.80, 0.95)) -> np.ndarray:
    flat = np.asarray(density, dtype=np.float64).reshape(-1)
    order = np.argsort(flat)[::-1]
    sorted_d = flat[order]
    cumulative = np.cumsum(sorted_d)
    cumulative /= cumulative[-1]
    levels = []
    for mass in masses:
        idx = min(int(np.searchsorted(cumulative, mass)), len(sorted_d) - 1)
        levels.append(sorted_d[idx])
    return np.asarray(sorted(set(levels)), dtype=np.float64)


def save_model(path: Path, model: WeightSpaceBayesTransport, cfg: Config = CFG) -> None:
    path = Path(path)
    eqx.tree_serialise_leaves(path, model)
    with path.with_suffix(".json").open("w") as f:
        json.dump(asdict(cfg), f, indent=2)


def load_model(path: Path, cfg: Config = CFG) -> WeightSpaceBayesTransport:
    template = WeightSpaceBayesTransport(cfg, key=jax.random.key(cfg.seed))
    return eqx.tree_deserialise_leaves(Path(path), template)


def evaluate_bt_weights(
    model: WeightSpaceBayesTransport,
    prior_particles: np.ndarray,
    x: np.ndarray = X_OBS,
) -> np.ndarray:
    """Return generated output-density weights/biases, never posterior particles."""
    seq = model(
        jnp.asarray(prior_particles),
        jnp.asarray(x),
        key=None,
        inference=True,
    )
    return np.asarray(jax.device_get(seq[..., 0]), dtype=np.float32)


def generated_density_on_grid(
    flat_parameters: np.ndarray,
    theta1_grid: np.ndarray,
    theta2_grid: np.ndarray,
    *,
    chunk_size: int = 8192,
    normalize_for_plot: bool | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Directly evaluate the generated neural density/score at requested theta locations.

    Returns (display_density, raw_log_values). In unnormalized mode, display_density is numerically
    normalized on the plotting grid ONLY for diagnostics; training never uses this normalization.
    """
    g1, g2 = np.meshgrid(theta1_grid, theta2_grid, indexing="xy")
    points = np.column_stack([g1.ravel(), g2.ravel()]).astype(np.float32)
    flat = jnp.asarray(flat_parameters, dtype=jnp.float32)

    chunks = []
    for start in range(0, len(points), int(chunk_size)):
        chunk = jnp.asarray(points[start:start + int(chunk_size)])
        values = generated_density_log_value(flat, chunk)
        chunks.append(np.asarray(jax.device_get(values), dtype=np.float64))
    log_values = np.concatenate(chunks).reshape(g1.shape)

    finite = np.isfinite(log_values)
    if not np.any(finite):
        raise FloatingPointError("Generated density/score is non-finite everywhere on the grid.")
    if CFG.output_density_mode == "realnvp":
        # Keep the actual normalized density scale. Values outside the compact support are -inf.
        density = np.where(finite, np.exp(log_values), 0.0)
    else:
        # An unnormalized score has arbitrary additive scale, so remove its maximum before exponentiating.
        shifted = np.where(finite, log_values - np.max(log_values[finite]), -np.inf)
        density = np.exp(shifted)

    if normalize_for_plot is None:
        # A RealNVP is already analytically normalized. The unnormalized MLP is normalized only
        # on this finite grid for visualization/diagnostic sampling.
        normalize_for_plot = CFG.output_density_mode == "unnormalized_mlp"

    if normalize_for_plot:
        d1 = theta1_grid[1] - theta1_grid[0]
        d2 = theta2_grid[1] - theta2_grid[0]
        z = np.sum(density) * d1 * d2
        if np.isfinite(z) and z > 0:
            density /= z
    return density, log_values


def generated_posterior_samples(
    flat_parameters: np.ndarray,
    theta1_grid: np.ndarray,
    theta2_grid: np.ndarray,
    n: int,
    seed: int,
) -> np.ndarray:
    if CFG.output_density_mode == "realnvp":
        samples = generated_realnvp_sample(
            jnp.asarray(flat_parameters), jax.random.key(seed), int(n)
        )
        return np.asarray(jax.device_get(samples), dtype=np.float32)

    # Experimental unnormalized mode: grid-normalize the score for diagnostic sampling only.
    density, _ = generated_density_on_grid(flat_parameters, theta1_grid, theta2_grid)
    return sample_from_grid_posterior(
        np.random.default_rng(seed), theta1_grid, theta2_grid, density, int(n)
    )


def rolling_mean(x: np.ndarray, window: int = 100) -> np.ndarray:
    x = np.asarray(x, dtype=np.float64)
    if len(x) < 2:
        return x.copy()
    window = max(1, min(int(window), len(x)))
    kernel = np.ones(window, dtype=np.float64) / window
    y = np.convolve(x, kernel, mode="valid")
    return np.concatenate([np.full(window - 1, np.nan), y])


def plot_training_diagnostics(history: dict[str, list[float]], cfg: Config = CFG) -> None:
    step = np.asarray(history["step"])
    sims = np.asarray(history["simulations_seen"])
    loss = np.asarray(history["target_nll"])

    fig, axes = plt.subplots(3, 2, figsize=(15, 14))

    axes[0, 0].plot(step, loss, alpha=0.30, label="Target NLL" if cfg.output_density_mode == "realnvp" else "Negative raw score")
    axes[0, 0].plot(step, rolling_mean(loss, 100), linewidth=2, label="100-step mean")
    axes[0, 0].set_title("Weight-space Bayes Transport training loss")
    axes[0, 0].set_xlabel("optimizer step")
    axes[0, 0].set_ylabel("negative log probability" if cfg.output_density_mode == "realnvp" else "negative score")
    axes[0, 0].legend()

    grad = np.maximum(np.asarray(history["grad_norm"]), 1e-16)
    axes[0, 1].plot(step, grad)
    axes[0, 1].set_yscale("log")
    axes[0, 1].set_title("Bayes Transport gradient norm")
    axes[0, 1].set_xlabel("optimizer step")
    axes[0, 1].set_ylabel("global norm")

    axes[1, 0].plot(step, history["mean_target_log_value"], label="Mean target log value")
    axes[1, 0].fill_between(
        step,
        np.asarray(history["mean_target_log_value"]) - np.asarray(history["target_log_value_std"]),
        np.asarray(history["mean_target_log_value"]) + np.asarray(history["target_log_value_std"]),
        alpha=0.18,
    )
    axes[1, 0].set_title("Generated density at simulator-known target")
    axes[1, 0].set_xlabel("optimizer step")
    axes[1, 0].set_ylabel("log density" if cfg.output_density_mode == "realnvp" else "raw log score")

    axes[1, 1].plot(step, history["generated_parameter_rms"], label="RMS")
    axes[1, 1].plot(step, history["generated_parameter_max_abs"], alpha=0.7, label="max |parameter|")
    axes[1, 1].set_title("Generated density-network weights/biases")
    axes[1, 1].set_xlabel("optimizer step")
    axes[1, 1].legend()

    axes[2, 0].plot(step, history["interpolation_fraction"], label="Interpolation")
    axes[2, 0].plot(step, history["buffer_fraction"], label="Buffer")
    axes[2, 0].plot(step, history["exact_prior_fraction"], label="Exact prior")
    axes[2, 0].set_ylim(-0.02, 1.02)
    axes[2, 0].set_title("Training input-cloud source mixture")
    axes[2, 0].set_xlabel("optimizer step")
    axes[2, 0].legend()

    axes[2, 1].plot(sims, loss, alpha=0.30, label="Loss")
    axes[2, 1].plot(sims, rolling_mean(loss, 100), linewidth=2, label="100-step mean")
    axes[2, 1].set_title("Loss versus simulator budget")
    axes[2, 1].set_xlabel("cumulative simulator calls")
    axes[2, 1].legend()

    fig.suptitle(
        f"Weight-space Bayes Transport diagnostics | mode={cfg.output_density_mode} | "
        f"final simulations={int(sims[-1]):,}",
        fontsize=16,
    )
    fig.tight_layout()
    fig.savefig(OUT / "10_training_diagnostics.png", dpi=180, bbox_inches="tight")
    plt.show()


def plot_prior_diagnostics(prior_samples: np.ndarray, cfg: Config = CFG) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(17, 5))
    axes[0].scatter(prior_samples[:, 0], prior_samples[:, 1], s=10, alpha=0.30)
    axes[0].set_xlim(cfg.prior_low, cfg.prior_high)
    axes[0].set_ylim(cfg.prior_low, cfg.prior_high)
    axes[0].set_aspect("equal", adjustable="box")
    axes[0].set_title(r"Exact evaluation prior $U([-1,1]^2)$")
    axes[0].set_xlabel(r"$\theta_1$")
    axes[0].set_ylabel(r"$\theta_2$")

    for d, label in enumerate([r"$\theta_1$", r"$\theta_2$"]):
        ax = axes[d + 1]
        ax.hist(prior_samples[:, d], bins=40, density=True, alpha=0.55)
        ax.hlines(1.0 / (cfg.prior_high - cfg.prior_low), cfg.prior_low, cfg.prior_high, linewidth=2)
        ax.set_xlim(cfg.prior_low - 0.1, cfg.prior_high + 0.1)
        ax.set_xlabel(label)
        ax.set_ylabel("density")
        ax.set_title(f"Prior marginal {label}")
    fig.tight_layout()
    fig.savefig(OUT / "20_exact_evaluation_prior.png", dpi=180, bbox_inches="tight")
    plt.show()


def plot_training_prior_examples(cfg: Config = CFG) -> None:
    rng = np.random.default_rng(cfg.seed + 700)
    theta_anchor = np.asarray([0.35, -0.20], dtype=np.float32)
    taus = [
        cfg.prior_interpolation_tau_min,
        0.5 * (cfg.prior_interpolation_tau_min + cfg.prior_interpolation_tau_max),
        cfg.prior_interpolation_tau_max,
    ]
    base = sample_interpolation_base_cloud_np(rng, 1500, cfg)
    fig, axes = plt.subplots(1, 4, figsize=(18, 4.5), sharex=True, sharey=True)
    axes[0].scatter(base[:, 0], base[:, 1], s=5, alpha=0.25)
    axes[0].set_title(f"Interpolation base: {cfg.interpolation_base_cloud}")
    for ax, tau in zip(axes[1:], taus):
        cloud = (1.0 - tau) * base + tau * theta_anchor[None, :]
        ax.scatter(cloud[:, 0], cloud[:, 1], s=5, alpha=0.25)
        ax.scatter([theta_anchor[0]], [theta_anchor[1]], marker="*", s=120)
        ax.set_title(rf"$\tau={tau:.2f}$")
    for ax in axes:
        ax.set_xlabel(r"$\theta_1$")
        ax.set_ylabel(r"$\theta_2$")
        ax.set_aspect("equal", adjustable="box")
    fig.suptitle("Training-only input-cloud interpolation geometry")
    fig.tight_layout()
    fig.savefig(OUT / "21_training_prior_interpolation.png", dpi=180, bbox_inches="tight")
    plt.show()


def plot_true_posterior_viridis(theta1: np.ndarray, theta2: np.ndarray, density: np.ndarray) -> None:
    fig, ax = plt.subplots(figsize=(7.0, 6.5))
    im = ax.imshow(
        density,
        origin="lower",
        extent=[theta1[0], theta1[-1], theta2[0], theta2[-1]],
        cmap="viridis",
        aspect="equal",
    )
    ax.set_xlabel(r"$\theta_1$")
    ax.set_ylabel(r"$\theta_2$")
    ax.set_title(r"Ground-truth $p(\theta\mid x_o)$ for $x_o=(0,0)$")
    fig.colorbar(im, ax=ax, label="posterior density")
    fig.tight_layout()
    fig.savefig(OUT / "30_true_posterior_viridis.png", dpi=180, bbox_inches="tight")
    plt.show()


def plot_figure1_style(
    theta1: np.ndarray,
    theta2: np.ndarray,
    exact_density: np.ndarray,
    snapshots: dict[int, tuple[int, np.ndarray]],
    cfg: Config = CFG,
) -> None:
    budgets = [b for b in cfg.figure1_simulation_budgets if b in snapshots]
    fig, axes = plt.subplots(1, 1 + len(budgets), figsize=(4.0 * (1 + len(budgets)), 4.1), squeeze=False)
    axes = axes.ravel()

    axes[0].imshow(
        exact_density / max(float(np.max(exact_density)), 1e-12),
        origin="lower",
        extent=[cfg.prior_low, cfg.prior_high, cfg.prior_low, cfg.prior_high],
        cmap="viridis", vmin=0, vmax=1, aspect="equal",
    )
    axes[0].set_title("True posterior")

    for ax, budget in zip(axes[1:], budgets):
        sims_seen, flat_parameters = snapshots[budget]
        d, _ = generated_density_on_grid(flat_parameters, theta1, theta2)
        d = d / max(float(np.max(d)), 1e-12)
        ax.imshow(
            d, origin="lower",
            extent=[cfg.prior_low, cfg.prior_high, cfg.prior_low, cfg.prior_high],
            cmap="viridis", vmin=0, vmax=1, aspect="equal",
        )
        ax.set_title(f"BT target N={budget:,}\nactual N={sims_seen:,}")

    for ax in axes:
        ax.set_xlim(cfg.prior_low, cfg.prior_high)
        ax.set_ylim(cfg.prior_low, cfg.prior_high)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.grid(False)
    fig.suptitle("Two moons — weight-space Bayes Transport analogue of Figure 1", fontsize=15)
    fig.tight_layout()
    fig.savefig(OUT / "31_figure1_style_weight_space_viridis.png", dpi=220, bbox_inches="tight")
    plt.show()


def plot_density_comparison(
    theta1: np.ndarray,
    theta2: np.ndarray,
    exact_density: np.ndarray,
    predicted_density: np.ndarray,
    predicted_log_values: np.ndarray,
    samples: np.ndarray,
) -> None:
    exact_shape = exact_density / max(float(np.max(exact_density)), 1e-12)
    pred_shape = predicted_density / max(float(np.max(predicted_density)), 1e-12)
    levels = credible_density_levels(exact_density)

    fig, axes = plt.subplots(2, 2, figsize=(12, 11))
    axes[0, 0].imshow(
        exact_shape, origin="lower",
        extent=[theta1[0], theta1[-1], theta2[0], theta2[-1]],
        cmap="viridis", vmin=0, vmax=1, aspect="equal",
    )
    axes[0, 0].set_title("Ground-truth posterior")

    axes[0, 1].imshow(
        pred_shape, origin="lower",
        extent=[theta1[0], theta1[-1], theta2[0], theta2[-1]],
        cmap="viridis", vmin=0, vmax=1, aspect="equal",
    )
    label = "Generated RealNVP density" if CFG.output_density_mode == "realnvp" else "Generated unnormalized score (grid-normalized)"
    axes[0, 1].set_title(label)

    axes[1, 0].imshow(
        pred_shape - exact_shape, origin="lower",
        extent=[theta1[0], theta1[-1], theta2[0], theta2[-1]],
        cmap="coolwarm", aspect="equal",
    )
    axes[1, 0].set_title("Predicted shape - exact shape")

    axes[1, 1].contour(theta1, theta2, exact_density, levels=levels, cmap="viridis", linewidths=1.6)
    axes[1, 1].scatter(samples[:, 0], samples[:, 1], s=8, alpha=0.28)
    axes[1, 1].set_title("Samples from generated output + exact contours")

    for ax in axes.ravel():
        ax.set_xlim(CFG.prior_low, CFG.prior_high)
        ax.set_ylim(CFG.prior_low, CFG.prior_high)
        ax.set_aspect("equal", adjustable="box")
        ax.set_xlabel(r"$\theta_1$")
        ax.set_ylabel(r"$\theta_2$")
        ax.grid(False)
    fig.tight_layout()
    fig.savefig(OUT / "32_final_density_comparison.png", dpi=200, bbox_inches="tight")
    plt.show()

    fig, ax = plt.subplots(figsize=(8, 6))
    finite = predicted_log_values[np.isfinite(predicted_log_values)]
    ax.hist(finite, bins=80, alpha=0.7)
    ax.set_title("Generated network log-density values on evaluation grid" if CFG.output_density_mode == "realnvp" else "Generated network raw log-scores on evaluation grid")
    ax.set_xlabel("log density" if CFG.output_density_mode == "realnvp" else "raw score")
    ax.set_ylabel("grid locations")
    fig.tight_layout()
    fig.savefig(OUT / "33_output_log_value_histogram.png", dpi=180, bbox_inches="tight")
    plt.show()


def plot_marginals_from_grid(
    theta1: np.ndarray,
    theta2: np.ndarray,
    exact_density: np.ndarray,
    predicted_density: np.ndarray,
) -> None:
    d1, d2 = theta1[1] - theta1[0], theta2[1] - theta2[0]
    exact_marg1 = np.sum(exact_density, axis=0) * d2
    exact_marg2 = np.sum(exact_density, axis=1) * d1
    pred_marg1 = np.sum(predicted_density, axis=0) * d2
    pred_marg2 = np.sum(predicted_density, axis=1) * d1

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    axes[0].plot(theta1, exact_marg1, linewidth=2, label="Ground truth")
    axes[0].plot(theta1, pred_marg1, linewidth=2, label="Weight-space BT")
    axes[0].set_xlabel(r"$\theta_1$")
    axes[0].set_ylabel("density")
    axes[0].set_title(r"Posterior marginal $\theta_1$")
    axes[0].legend()

    axes[1].plot(theta2, exact_marg2, linewidth=2, label="Ground truth")
    axes[1].plot(theta2, pred_marg2, linewidth=2, label="Weight-space BT")
    axes[1].set_xlabel(r"$\theta_2$")
    axes[1].set_ylabel("density")
    axes[1].set_title(r"Posterior marginal $\theta_2$")
    axes[1].legend()
    fig.tight_layout()
    fig.savefig(OUT / "34_posterior_marginals.png", dpi=180, bbox_inches="tight")
    plt.show()


def plot_generated_parameter_vector(flat_parameters: np.ndarray) -> None:
    p = np.asarray(flat_parameters, dtype=np.float64)
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    axes[0].plot(np.arange(len(p)), p, linewidth=0.7)
    axes[0].set_xlabel("generated parameter index")
    axes[0].set_ylabel("value")
    axes[0].set_title("Generated density weights and biases")
    axes[1].hist(p, bins=80, density=True, alpha=0.65)
    axes[1].set_xlabel("parameter value")
    axes[1].set_ylabel("density")
    axes[1].set_title("Distribution of generated parameters")
    fig.tight_layout()
    fig.savefig(OUT / "35_generated_density_parameters.png", dpi=180, bbox_inches="tight")
    plt.show()


def plot_posterior_predictive(samples: np.ndarray, cfg: Config = CFG) -> None:
    rng = np.random.default_rng(cfg.seed + 8800)
    ids = rng.choice(len(samples), size=min(5000, len(samples)), replace=True)
    x_pp = simulate_two_moons_batch_np(rng, samples[ids])
    fig, ax = plt.subplots(figsize=(7.3, 7.0))
    h = ax.hist2d(x_pp[:, 0], x_pp[:, 1], bins=120, cmap="viridis", density=True)
    ax.scatter([X_OBS[0]], [X_OBS[1]], marker="*", s=250, c="white", edgecolors="black", linewidths=1.2)
    ax.set_xlabel(r"$x_1$")
    ax.set_ylabel(r"$x_2$")
    ax.set_title("Posterior predictive simulator outputs")
    ax.set_aspect("equal", adjustable="box")
    fig.colorbar(h[3], ax=ax, label="predictive density")
    fig.tight_layout()
    fig.savefig(OUT / "36_posterior_predictive.png", dpi=180, bbox_inches="tight")
    plt.show()


def posterior_summary(samples: np.ndarray) -> dict[str, Any]:
    samples = np.asarray(samples, dtype=np.float64)
    return {
        "mean": np.mean(samples, axis=0),
        "cov": np.cov(samples.T),
        "outside_prior_fraction": float(np.mean(np.any((samples < CFG.prior_low) | (samples > CFG.prior_high), axis=1))),
    }


def energy_distance_samples(a: np.ndarray, b: np.ndarray, max_n: int = 2500) -> float:
    rng = np.random.default_rng(123)
    a, b = np.asarray(a, dtype=np.float64), np.asarray(b, dtype=np.float64)
    if len(a) > max_n:
        a = a[rng.choice(len(a), max_n, replace=False)]
    if len(b) > max_n:
        b = b[rng.choice(len(b), max_n, replace=False)]
    ab = np.linalg.norm(a[:, None, :] - b[None, :, :], axis=-1).mean()
    aa = np.linalg.norm(a[:, None, :] - a[None, :, :], axis=-1).mean()
    bb = np.linalg.norm(b[:, None, :] - b[None, :, :], axis=-1).mean()
    return float(2.0 * ab - aa - bb)


def sliced_wasserstein(a: np.ndarray, b: np.ndarray, n_proj: int = 128) -> float:
    rng = np.random.default_rng(456)
    a, b = np.asarray(a, dtype=np.float64), np.asarray(b, dtype=np.float64)
    n = min(len(a), len(b), 5000)
    a = a[rng.choice(len(a), n, replace=False)]
    b = b[rng.choice(len(b), n, replace=False)]
    directions = rng.normal(size=(n_proj, 2))
    directions /= np.linalg.norm(directions, axis=1, keepdims=True)
    return float(np.mean([np.mean(np.abs(np.sort(a @ u) - np.sort(b @ u))) for u in directions]))


def rbf_mmd2(a: np.ndarray, b: np.ndarray, max_n: int = 2500) -> float:
    rng = np.random.default_rng(789)
    a, b = np.asarray(a, dtype=np.float64), np.asarray(b, dtype=np.float64)
    if len(a) > max_n:
        a = a[rng.choice(len(a), max_n, replace=False)]
    if len(b) > max_n:
        b = b[rng.choice(len(b), max_n, replace=False)]
    pooled = np.concatenate([a, b], axis=0)
    m = min(len(pooled), 1200)
    probe = pooled[rng.choice(len(pooled), m, replace=False)]
    d2_probe = np.sum((probe[:, None, :] - probe[None, :, :]) ** 2, axis=-1)
    tri = d2_probe[np.triu_indices(m, k=1)]
    positive = tri[tri > 0]
    sigma2 = max(float(np.median(positive)) if len(positive) else 1.0, 1e-8)

    def kernel(x, y):
        d2 = np.sum((x[:, None, :] - y[None, :, :]) ** 2, axis=-1)
        return np.exp(-0.5 * d2 / sigma2)

    return float(kernel(a, a).mean() + kernel(b, b).mean() - 2.0 * kernel(a, b).mean())


def comparison_metrics(exact: np.ndarray, candidate: np.ndarray) -> dict[str, float]:
    e, c = posterior_summary(exact), posterior_summary(candidate)
    return {
        "mean_error": float(np.linalg.norm(c["mean"] - e["mean"])),
        "covariance_frobenius_error": float(np.linalg.norm(c["cov"] - e["cov"], ord="fro")),
        "outside_prior_fraction": float(c["outside_prior_fraction"]),
        "sliced_wasserstein": sliced_wasserstein(exact, candidate, CFG.sliced_wasserstein_projections),
        "energy_distance": energy_distance_samples(exact, candidate),
        "rbf_mmd2": rbf_mmd2(exact, candidate),
    }


THETA1_GRID, THETA2_GRID, EXACT_DENSITY = exact_posterior_grid(X_OBS, CFG)
_exact_rng = np.random.default_rng(CFG.seed + 500)
EXACT_SAMPLES = sample_from_grid_posterior(
    _exact_rng, THETA1_GRID, THETA2_GRID, EXACT_DENSITY, CFG.exact_reference_samples
)
plot_true_posterior_viridis(THETA1_GRID, THETA2_GRID, EXACT_DENSITY)


#%% 6) TRAIN WEIGHT-SPACE BAYES TRANSPORT — one trainable model, NLL only
train_rng = np.random.default_rng(CFG.seed + 10_001)
mode_rng = np.random.default_rng(CFG.seed + 20_003)
dropout_key = jax.random.key(CFG.seed + 30_007)
replay_key = jax.random.key(CFG.seed + 30_008)
replay_buffer = HistoricalPosteriorBuffer(
    CFG.historical_output_buffer_capacity,
    CFG.num_particles,
)

history = {k: [] for k in [
    "step",
    "simulations_seen",
    "target_nll",
    "mean_target_log_value",
    "target_log_value_std",
    "generated_parameter_rms",
    "generated_parameter_max_abs",
    "grad_norm",
    "interpolation_fraction",
    "buffer_fraction",
    "exact_prior_fraction",
    "mean_interpolation_tau",
    "mean_replay_distance",
    "buffer_size",
]}

_snapshot_rng = np.random.default_rng(CFG.seed + 40_009)
FIGURE1_PRIOR_PARTICLES = sample_exact_prior_np(_snapshot_rng, CFG.eval_particles)
figure1_snapshot_parameters: dict[int, tuple[int, np.ndarray]] = {}

for step in range(1, CFG.training_steps + 1):
    # Fresh simulator-supervised minibatch.
    theta_target = sample_exact_prior_np(train_rng, CFG.batch_size)
    x_batch = simulate_two_moons_batch_np(train_rng, theta_target)

    # Same mutually-exclusive input-cloud mixture as before.
    prior_theta, prior_info = make_training_prior_batch_np(
        train_rng, mode_rng, theta_target, x_batch, replay_buffer, CFG
    )

    # Single gradient update. The transport emits density weights/biases; the NLL is evaluated at theta*.
    dropout_key, step_key = jax.random.split(dropout_key)
    model, opt_state, loss, metrics, parameter_sequence, grad_norm = train_step(
        model,
        opt_state,
        jnp.asarray(prior_theta),
        jnp.asarray(x_batch),
        jnp.asarray(theta_target),
        step_key,
    )

    # Historical replay remains available. We sample from the generated density only to construct the
    # next step's optional replay input cloud; these samples are NOT model outputs and do not enter NLL.
    flat_batch = parameter_sequence[..., 0]
    replay_key, replay_step_key = jax.random.split(replay_key)
    replay_clouds = sample_replay_cloud_batch(flat_batch, replay_step_key)
    replay_buffer.add_batch(
        x_batch,
        np.asarray(jax.device_get(replay_clouds), dtype=np.float32),
    )

    host = jax.device_get(metrics)
    interp_tau = prior_info["interpolation_tau"]
    replay_dist = prior_info["replay_distance"]
    positive_tau = interp_tau[prior_info["interpolation_used"] > 0]
    finite_replay_dist = replay_dist[np.isfinite(replay_dist)]

    scalar_values = {
        "step": float(step),
        "simulations_seen": float(step * CFG.batch_size),
        "target_nll": float(host["target_nll"]),
        "mean_target_log_value": float(host["mean_target_log_value"]),
        "target_log_value_std": float(host["target_log_value_std"]),
        "generated_parameter_rms": float(host["generated_parameter_rms"]),
        "generated_parameter_max_abs": float(host["generated_parameter_max_abs"]),
        "grad_norm": float(jax.device_get(grad_norm)),
        "interpolation_fraction": float(np.mean(prior_info["interpolation_used"])),
        "buffer_fraction": float(np.mean(prior_info["buffer_used"])),
        "exact_prior_fraction": float(np.mean(prior_info["exact_prior_used"])),
        "mean_interpolation_tau": float(np.mean(positive_tau)) if len(positive_tau) else np.nan,
        "mean_replay_distance": float(np.mean(finite_replay_dist)) if len(finite_replay_dist) else np.nan,
        "buffer_size": float(len(replay_buffer)),
    }
    for name, value in scalar_values.items():
        history[name].append(value)

    previous_simulations = (step - 1) * CFG.batch_size
    current_simulations = step * CFG.batch_size
    for budget in CFG.figure1_simulation_budgets:
        if budget not in figure1_snapshot_parameters and previous_simulations < budget <= current_simulations:
            figure1_snapshot_parameters[budget] = (
                current_simulations,
                evaluate_bt_weights(model, FIGURE1_PRIOR_PARTICLES, X_OBS),
            )

    if step == 1 or step % CFG.log_every == 0 or step == CFG.training_steps:
        loss_name = "NLL" if CFG.output_density_mode == "realnvp" else "negative-score"
        print(
            f"step {step:6d}/{CFG.training_steps} | "
            f"sims {step * CFG.batch_size:9,d} | "
            f"{loss_name} {scalar_values['target_nll']:.5f} | "
            f"grad {scalar_values['grad_norm']:.2e} | "
            f"param-rms {scalar_values['generated_parameter_rms']:.3e} | "
            f"prior i/b/e="
            f"{scalar_values['interpolation_fraction']:.2f}/"
            f"{scalar_values['buffer_fraction']:.2f}/"
            f"{scalar_values['exact_prior_fraction']:.2f}"
        )

save_model(OUT / "bayes_transport_two_moons_weight_space_v4.eqx", model, CFG)

with (OUT / "training_history.csv").open("w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=list(history.keys()))
    writer.writeheader()
    for i in range(len(history["step"])):
        writer.writerow({k: history[k][i] for k in history})

plot_training_diagnostics(history, CFG)
plot_training_prior_examples(CFG)

_eval_prior_rng = np.random.default_rng(CFG.seed + 60_011)
EVAL_PRIOR_PARTICLES = sample_exact_prior_np(_eval_prior_rng, CFG.eval_particles)
plot_prior_diagnostics(EVAL_PRIOR_PARTICLES, CFG)
plot_figure1_style(
    THETA1_GRID,
    THETA2_GRID,
    EXACT_DENSITY,
    figure1_snapshot_parameters,
    CFG,
)


#%% 7) FINAL EVALUATION — exact prior cloud -> generated density weights/biases
# To evaluate a saved checkpoint without retraining, run instead:
# model = load_model(OUT / "bayes_transport_two_moons_weight_space_v4.eqx", CFG)

if "EVAL_PRIOR_PARTICLES" not in globals():
    _eval_prior_rng = np.random.default_rng(CFG.seed + 60_011)
    EVAL_PRIOR_PARTICLES = sample_exact_prior_np(_eval_prior_rng, CFG.eval_particles)

# This is the Bayes-Transport output: one scalar sequence containing every density-network weight/bias.
BT_DENSITY_PARAMETERS = evaluate_bt_weights(model, EVAL_PRIOR_PARTICLES, X_OBS)
print("Generated parameter sequence shape:", BT_DENSITY_PARAMETERS[:, None].shape)

# Direct neural-density evaluation at arbitrary theta grid locations.
BT_DENSITY, BT_LOG_VALUES = generated_density_on_grid(
    BT_DENSITY_PARAMETERS,
    THETA1_GRID,
    THETA2_GRID,
)

# Samples are optional diagnostics derived FROM the generated density; they are not transformer outputs.
BT_POSTERIOR_SAMPLES = generated_posterior_samples(
    BT_DENSITY_PARAMETERS,
    THETA1_GRID,
    THETA2_GRID,
    CFG.exact_reference_samples,
    CFG.seed + 70_013,
)

plot_density_comparison(
    THETA1_GRID,
    THETA2_GRID,
    EXACT_DENSITY,
    BT_DENSITY,
    BT_LOG_VALUES,
    BT_POSTERIOR_SAMPLES,
)
plot_marginals_from_grid(THETA1_GRID, THETA2_GRID, EXACT_DENSITY, BT_DENSITY)
plot_generated_parameter_vector(BT_DENSITY_PARAMETERS)
plot_posterior_predictive(BT_POSTERIOR_SAMPLES, CFG)

metrics = comparison_metrics(EXACT_SAMPLES, BT_POSTERIOR_SAMPLES)
print("\nGround-truth posterior summary:")
print(posterior_summary(EXACT_SAMPLES))
print("\nWeight-space Bayes Transport posterior summary:")
print(posterior_summary(BT_POSTERIOR_SAMPLES))
print("\nComparison metrics:")
for k, v in metrics.items():
    print(f"  {k}: {v:.8f}")

# Numerical grid integral: should be close to 1 in RealNVP mode because q is exactly normalized.
_grid_d1 = THETA1_GRID[1] - THETA1_GRID[0]
_grid_d2 = THETA2_GRID[1] - THETA2_GRID[0]
print("Grid integral of displayed output density:", float(np.sum(BT_DENSITY) * _grid_d1 * _grid_d2))

with (OUT / "final_metrics.csv").open("w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=list(metrics.keys()))
    writer.writeheader()
    writer.writerow(metrics)

np.save(OUT / "evaluation_prior_particles.npy", EVAL_PRIOR_PARTICLES)
np.save(OUT / "generated_density_parameters.npy", BT_DENSITY_PARAMETERS)
np.save(OUT / "generated_posterior_density_grid.npy", BT_DENSITY)
np.save(OUT / "generated_posterior_samples.npy", BT_POSTERIOR_SAMPLES)
np.save(OUT / "ground_truth_posterior_samples.npy", EXACT_SAMPLES)
np.save(OUT / "observed_x.npy", X_OBS)


#%% 8) Compact publication-style panel: prior | exact | generated density | direct contours | samples
_levels = credible_density_levels(EXACT_DENSITY)
fig, axes = plt.subplots(1, 5, figsize=(21, 4.2))

axes[0].scatter(EVAL_PRIOR_PARTICLES[:, 0], EVAL_PRIOR_PARTICLES[:, 1], s=7, alpha=0.30)
axes[0].set_title("Exact test prior")

axes[1].imshow(
    EXACT_DENSITY / max(float(np.max(EXACT_DENSITY)), 1e-12),
    origin="lower",
    extent=[CFG.prior_low, CFG.prior_high, CFG.prior_low, CFG.prior_high],
    cmap="viridis", vmin=0, vmax=1, aspect="equal",
)
axes[1].set_title("Ground truth")

axes[2].imshow(
    BT_DENSITY / max(float(np.max(BT_DENSITY)), 1e-12),
    origin="lower",
    extent=[CFG.prior_low, CFG.prior_high, CFG.prior_low, CFG.prior_high],
    cmap="viridis", vmin=0, vmax=1, aspect="equal",
)
axes[2].set_title("Generated density")

axes[3].contour(THETA1_GRID, THETA2_GRID, EXACT_DENSITY, levels=_levels, cmap="viridis", linewidths=1.4)
axes[3].contour(THETA1_GRID, THETA2_GRID, BT_DENSITY, levels=credible_density_levels(BT_DENSITY), linewidths=1.2)
axes[3].set_title("Exact + generated contours")

axes[4].contour(THETA1_GRID, THETA2_GRID, EXACT_DENSITY, levels=_levels, cmap="viridis", linewidths=1.4)
axes[4].scatter(BT_POSTERIOR_SAMPLES[:, 0], BT_POSTERIOR_SAMPLES[:, 1], s=6, alpha=0.25)
axes[4].set_title("Samples from generated density")

for ax in axes:
    ax.set_xlim(CFG.prior_low, CFG.prior_high)
    ax.set_ylim(CFG.prior_low, CFG.prior_high)
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel(r"$\theta_1$")
    ax.set_ylabel(r"$\theta_2$")
    ax.grid(False)

fig.suptitle(
    rf"Two moons — weight-space Bayes Transport | mode={CFG.output_density_mode}",
    fontsize=15,
)
fig.tight_layout()
fig.savefig(OUT / "50_compact_publication_panel.png", dpi=220, bbox_inches="tight")
plt.show()
